### ISSUE TITLE
Add Python Logger to Packages

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/denspp.offline#77]
# Logging

Python provides simple log output with the `logging` module. Alongside with the (logdecorator)[https://github.com/sighalt/logdecorator) package, it can provide simple logging supprt for the application and it's modules.

## ToDo's

- [x] Add `log.py` to packages folder
- [x] Import `logging` in script
- [x] Import `logdecorator` in script
- [x] Provide setup function for simple setup
